/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quran;

//import javax.swing.JFrame;
import java.awt.Toolkit;

public class mainPage extends javax.swing.JFrame {

    static boolean start = false;

    public mainPage() {
        // this.setUndecorated(true);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        MainButton.setBackground(new java.awt.Color(9, 4, 4));
        MainButton.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        MainButton.setForeground(new java.awt.Color(9, 4, 4));
        MainButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/QURA.jpeg"))); // NOI18N
        MainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MainButton);
        MainButton.setBounds(580, 290, 220, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1-islamic-motives-corporate-art-task-force.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(950, 0, 500, 780);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/18763062_1767192470257796_47852208_n.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-80, 0, 470, 780);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1-islamic-motives-corporate-art-task-force.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 0, 740, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainButtonActionPerformed
        try {

            start = true;
            this.setVisible(false);
            new menuPage().setVisible(true);

        } catch (Exception e) {
        }


    }//GEN-LAST:event_MainButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
            
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
